// import store from '../store'
//
// const languageList = {
//     "en": {
//         ACCOUNT: "Account",
//         PASSWORD: "Password",
//         LOG_In: "Login",
//         LOG_OUT: "Logout",
//         ChANG_PASSWORD: "Change password",
//         CurrentPassword: "Current password",
//         NEWPassword: "New password",
//         AGAIN_NEWPassword: "Enter new password again",
//         SUBMIT: "Submit",
//         SURE: "Confirm",
//         CANCEL: "Cancel",
//         CLOSE: "Close",
//         ADMIN_MANAGEMENT: "Background management",
//         // 数据概览                                                              Data overview",
//         DATA_BOARD: "Data overview",
//         VEHICLE: "Vehicle",
//         USER: "User",
//         VEHICLE_ALL_NUM: "Total number of vehicles",
//         VEHICLE_ONLINE: "Online vehicles",
//         VEHICLE_OFFLINE: "Offline vehicle",
//         VEHICLE_NEW: "Newly tied vehicles in the last 30 days",
//         DATA_VEHICLE_LOCATION: "Current vehicle distribution",
//         DATA_VEHICLE_CITY: "The city where the vehicle is located",
//         DATA_VEHICLE_NEW: "Number of newly bound vehicles",
//         DATA_VEHICLE_SALE: "Total number of vehicles sold (bind APP)",
//         DATA_VEHICLE_SALE_CITY: "Vehicle sold (bind APP) city TOP10",
//         RANK: "Ration",
//         CITY: "City",
//         VEHICLE_NUM: "Number of vehicles",
//         DATE: "Date",
//         USER_ALL_NUM: "Total number of users",
//         DATA_USER_NEW: "New registered user",
//         DATA_USER_LOCATION: "The distribution of the user's location",
//         DATA_USER_CITY: "User's city TOP10",
//         USER_NUM: "Number of users",
//         // 车辆管理                                                              Vehicle management",
//         BREADCRUMB_VEHICLE: "Vehicle management",
//         VEHICLE_LIST: "Vehicle list",
//         VEHICLE_ID_CODE: "Vehicle identification number",
//         FRAME_ID: "frame number",
//         VCU_ID: "VCU number",
//         VEHICLE_TYPE: "Model",
//         CONFIGURATION_ID: "Configuration number",
//         OWNER_ID: "Car owner account",
//         FIRST_BIND_LOCATION: "First binding area",
//         FIRST_BIND_DATE: "First bind time",
//         CONNECTION: "Is it online",
//         LAST_ONLINE_TIME: "Last online time",
//         OPERATION: "Operation",
//         IMPORT_VEHICLES: "Import vehicle",
//         DOWNLOAD_VEHICLES: "Export vehicle",
//         DETAIL: "Details",
//         DRIVING_RECORD: "Travel record",
//         REPORT_BOOK: "Physical examination report",
//         ONLINE: "Online",
//         OFFLINE: "Offline",
//         ALL: "All",
//         TOTAL: "Total",
//         // 车辆详情                                                              Vehicle details",
//         VEHICLE_DETAIL: "Vehicle details",
//         VEHICLE_DETAIL_INFO: "Vehicle basic information",
//         VEHICLE_DETAIL_PARTS: "Vehicle accessories information",
//         VEHICLE_DETAIL_USE: "Vehicle usage",
//         VEHICLE_DETAIL_SERVICE: "Current smart service",
//         VEHICLE_DETAIL_OWNER: "Car owner information",
//         VEHICLE_COLOR: "Color",
//         VEHICLE_UPDATE: "Update",
//         VEHICLE_CONFIG: "Model configuration",
//         VIEW_MORE: "View more",
//         VEHICLE_CLOSE: "Put away",
//         VEHICLE_LOCKING: "Remote lock car",
//         VEHICLE_LOCKING_TIP: "Are you sure to lock the car",
//         VEHICLE_DJ: "Motor no",
//         VEHICLE_KZQ: "Motor controller number",
//         VEHICLE_YB: "Meter number",
//         VEHICLE_BMS: "BMS number",
//         VEHICLE_CDQ: "Charger number",
//         VEHICLE_BJQ: "Alarm number",
//         VEHICLE_DGKZ: "Lighting controller number",
//         VEHICLE_USE_DATE: "Usage time (days)",
//         VEHICLE_TRIP: "Accumulated trip (km)",
//         VEHICLE_TRIP_TIME: "Accumulated driving time",
//         VEHICLE_NOW_lOC: "The current location of the vehicle",
//         VEHICLE_SPEED: "Average speed",
//         VEHICLE_SPEED_MUST: "Maximum speed",
//         HOUR: "Hours",
//         MINUTE: "Minutes",
//         SECOND: "Second",
//         VIEW: "View",
//         VEHICLE_NOW_lOC_DETAIL: "View the current location of the vehicle",
//         GPS: "GPS coordinates",
//         ADDRESS: "Address",
//         UPDATE_TIME: "Update time",
//         DRIVING_RECORD_DETAIL: "View driving history",
//         PACKAGE_TYPE: "Package type",
//         MATURITY_TIME: "Expiration time",
//         MAIN_ACCOUNT: "Primary account",
//         SUB_ACCOUNT: "From account",
//         BINDING_TIME: "Binding time",
//         UNBINDING_TIME: "Untie time",
//         HISTORIC_OWNERS: "History owner",
//         HISTORIC_OWNERS_DETAIL: "View historical owner information",
//         UNBOUND_VEHICLES: "Untie the vehicle",
//         UNBOUND_VEHICLES_TIP: "Are you sure to untie the vehicle?",
//         MODIFY: "Modify",
//         SAVE: "Save",
//         // 车辆行驶历史                                                            Vehicle history",
//         DRIVING_RECORD_HIS: "Vehicle driving history",
//         DRIVING_RECORD_LJXS: "Accumulated driving",
//         DRIVING_TIME_START: "Riding time (starting)",
//         DRIVING_TIME_END: "ride time (final)",
//         START_LOC: "Starting point",
//         END_LOC: "End point",
//         DRIVING_KM: "Traveling miles (km)",
//         DRIVING_TIME: "Travel time",
//         TRAJECTORY: "Track",
//         TRAJECTORY_VIEW: "View tracks",
//         TRAJECTORY_DETAIL: "Vehicle trajectory",
//         // 车辆体检报告                                                            Vehicle medical report",
//         VEHICLES_REPORT_BOOK: "Physical examination report",
//         REPORT_RESULT: "Physical examination result",
//         REPORT_NUM: "Number of physical exams",
//         REPORT_DL: "Power system abnormal number",
//         REPORT_DY: "Power system abnormal number",
//         REPORT_AF: "Security aystem abnormal number of times",
//         REPORT_TX: "Number of communication system anomalies",
//         REPORT_ZM: "Number of illumination system anomalies",
//         REPORT_TIME: "Physical examination time",
//         REPORT_XT_DL: "Power aystem",
//         REPORT_XT_DY: "Power aystem",
//         REPORT_XT_AF: "Security System",
//         REPORT_XT_TX: "Communication system",
//         REPORT_XT_ZM: "Lighting system",
//         NORMAL: "Normal",
//         ABNORMAL: "Exception",
//         HAVE_ABNORMAL: "There is an exception",
//         REPORT_AB_DL: "Power system abnormal",
//         REPORT_AB_DY: "Power system is abnormal",
//         REPORT_AB_AF: "Security system abnormal",
//         REPORT_AB_TX: "Communication system exception",
//         REPORT_AB_ZM: "The lighting system is abnormal",
//         REPORT_DETAIL: "Details of the medical report",
//         // 车型管理                                                              Model management",
//         VEHICLE_TYPE_MAN: "Model management",
//         PICTURE: "Picture",
//         IS_PICTURE: "Have a picture？",
//         IS_PICTURE_YES: "Yes",
//         IS_PICTURE_NO: "None",
//         VEHICLE_TYPE_IMPORT: "Imported models",
//         VEHICLE_TYPE_ADD: "Add a model",
//         EDIT: "Edit",
//         DELETE: "Delete",
//         VEHICLE_TYPE_INFO: "Model information",
//         VEHICLE_TYPE_INFO_TIP1: "The model, configuration number, and color that are associated with the vehicle are not editable",
//         VEHICLE_TYPE_INFO_TIP2: "1. Safe Range 470PX x 470PX (Vehicle Size Range)",
//         VEHICLE_TYPE_INFO_TIP3: "2. The file size is 500PX x 512PX",
//         VEHICLE_TYPE_INFO_TIP4: "3. Try to use the physical map as much as possible, the background color is recommended to be transparent, or the background color is #F9F9F9",
//         DELETE_TIP: "Are you sure to delete?",
//         // 用户管理                                                              User management",
//         USER_MAN: "User management",
//         USER_LIST: "User list",
//         USER_ID: "User account",
//         REAL_NAME: "Real name",
//         GENDER: "Gender",
//         USER_AREA: "Zone in the area",
//         REGISTRATION_TIME: "Registration time",
//         STATUS: "Status",
//         USER_EXPORT: "Export user",
//         DISABLE: "Disabled",
//         ABLE: "Enable",
//         DISABLE_TIP: "Are you sure to disable?",
//         ABLE_TIP: "Are you sure to enable?",
//         USER_CARD_ID: "ID number",
//         BIRTH: "Birthday",
//         IDENTITY: "Identity",
//         HISTORICAL_VEHICLES: "Historical vehicles",
//         // 消息管理                                                              message management",
//         MSG_MAN: "Message management",
//         MSG_LIST: "Message management list",
//         MSG_TITLE: "message topic",
//         MSG_TYPE: "message type",
//         MSG_TIME: "Push time",
//         MSG_ADD: "Add message",
//         MSG_EDIT: "Edit message",
//         MSG_TYPE_TZ: "Notification",
//         MSG_TYPE_HD: "Activity",
//         MSG_TYPE_QT: "Other",
//         MSG_DISC: "Message description",
//         MSG_DETAIL: "Message content",
//         MSG_TIME_INTERVAL: "Timed release",
//         MSG_AREA: "Publishing area",
//         MSG_SELECT_AREA: "Select region",
//         MSG_URL: "Add external link",
//         MSG_IMAGE: "Theme Picture",
//         MSG_IMAGE_TIP: "(image size 690*284px.)",
//         MSG_SELECT_AREA_TIP: "Please select a region",
//         //反馈管理                                                               Feedback management",
//         FEEDBACK_MAN: "Feedback management",
//         FEEDBACK_LIST: "Feedback list",
//         FEEDBACK_TYPE: "Feedback type",
//         FEEDBACK_DETAIL: "Feedback content",
//         FEEDBACK_TIME: "Feedback time",
//         EXPORT: "Export list",
//         FEEDBACK_DETAIL_VIEW: "Feedback information",
//         FEEDBACK_DETAIL_TIP: "Click to view image details",
//         //员工管理                                                               Employee management",
//         STAFF_MAN: "Employee management",
//         ROLE_LIST: "role list",
//         ROLE_NAME: "role name",
//         ROLE_ID: "role number",
//         ROLE_ADD: "Add a role",
//         ROLE_EDIT: "Edit role",
//         REMARK: "Remarks",
//         ROLE_DISTRIBUTION: "Assign a role",
//         //员工账号管理                                                             Staff account management",
//         STAFF_LIST: "Employee account list",
//         STAFF_USER_NAME: "Username",
//         STAFF_NAME: "Name",
//         ROLE: "Role",
//         TELEPHONE: "Mobile phone",
//         CREATED_TIME: "Create time",
//         STAFF_LAST_LOGIN: "Last login time",
//         STAFF_LAST_IP: "Last login iP",
//         STAFF_INFO: "Employee account information",
//         // 操作日志                                                              Operation log",
//         LOG_LIST: "Operation log",
//         TIME: "Time",
//         // 固件升级管理                                                            Firmware upgrade management",
//         Firmware_MAN: "Firmware upgrade management",
//         Firmware_UPDATE: "Firmware upgrade",
//         Firmware_ID: "Part product number",
//         Firmware_OLD_Version: "Original firmware version",
//         Firmware_NEW_Version: "Upgrade firmware version",
//         Firmware_Version_Description: "Firmware version description",
//         Firmware_UPDATE_ADD: "Upgrade firmware",
//         Firmware_OLD_Version_NO: "Original firmware version number",
//         Firmware_NEW_Version_NP: "New firmware version number",
//         Firmware_UPDATE_TYPE: "Upgrade type",
//         Firmware_Version_Description_NEW: "New firmware release Notes",
//         Firmware_FORCE: "Forced",
//         Firmware_USER_SELECTION: "User-selected",
//         Firmware_UPDATE_Version: "Upgrade firmware version number",
//         Firmware_UPDATE_Version_DOWOND: "Upgrade firmware download",
//         Firmware_UPDATE_Version_Description: "Upgrade firmware version description",
//         Firmware_TIP1: "Parts are being upgraded",
//         Firmware_TIP2: "The components are waiting for the upgrade",
//         Firmware_TIP3: "The components have been upgraded successfully",
//         Firmware_TIP4: "The vehicle is dropped",
//         Firmware_TIP5: "The device vCU download failed",
//         Firmware_TIP6: "Taiwan device 485 transmission failed",
//         Firmware_TIP7: "The device firmware failed to upgrade",
//         Firmware_TIP8: "The device 485 transmission failed.",
//         SEND_AGAIN: "Send again",
//         RE_DOWNLOAD: "Re-download",
//         // OTA 固件包                                                           OTA firmware package",
//         OTA_LIST: "OTA firmware package",
//         Firmware_Version: "Firmware version",
//         OTA_Version_Description: "Version description",
//         ADD_TIME: "Add time",
//         OTA_ADD: "Add firmware",
//         Version_ID: "Version number",
//         OTA_BAG: "Firmware pack",
//         OTA_Description: "Description",
//         // 广告管理                                                              Advertising management",
//         ADVERTISING_MAN: "Advertising management",
//         ADVERTISING_EDIT: "Replace ads",
//         ADVERTISING_EDIT_TIP: "Image size 750*1334 px, it is recommended that the image body does not exceed 710*1334px.",
//         ADVERTISING_RELEASE: "Publish",
//         //    APP管理                                                              APP management",
//         APP_MAN: "APP management",
//         APP_NAME: "Version name",
//         APP_TYPE: "APP type",
//         APP_SYS: "Operating system type",
//         APP_TIME: "Version time",
//         APP_ADD: "Add aPP version",
//         APP_UPLOAD: "Upload",
//         APP_LOG: "Version update log",
//         // 新闻管理                                                              News management",
//         NEWS_MAN: "News management",
//         NEWS_LIST: "News list",
//         NEWS_TITLE: "News headline",
//         NEWS_TOP: "Is it topped",
//         NEWS_TIME: "Publish time",
//         NEWS_ADD: "Add news",
//         NEWS_EDIT: "Editing news",
//         NEWS_NOW_PUSH: "Immediately released",
//         NEWS_FY: "Cover image",
//         NEWS_FY_TIP: "Only one image can be uploaded, the image size is greater than or equal to 80*80 px square image",
//         NEWS_DISC: "News introduction",
//         NEWS_DETAIL: "News details",
//         // 自检手册管理                                                            Self-test manual management",
//         INSPECTION_MAN: "Self-test manual management",
//         INSPECTION_CLASSIFICATION: "Self-test manual classification",
//         INSPECTION_TYPE: "Self-test type",
//         INSPECTION_RANK: "Sort",
//         INSPECTION_SON: "Subset",
//         INSPECTION_SON_AREA: "Subset area",
//         INSPECTION_CLASSIFICATION_EDIT: "Edit self-test classification",
//         // 自检内容管理                                                            Self-test content management",
//         INSPECTION_CONTENT: "Self-test content management",
//         INSPECTION_TITLE: "Self-test title",
//         INSPECTION_ASSOCIATION_TYPE: "association type",
//         INSPECTION_CODE: "Associated fault code",
//         INSPECTION_ADD: "Add self-test content",
//         INSPECTION_EDIT: "Edit self-test content",
//         INSPECTION_DETAIL: "Self-test content details",
//         INSPECTION_DESC: "problem symptom",
//         INSPECTION_PROBLEM_DETAIL: "Uestion details",
//         INSPECTION_SOLVE: "Solution",
//         INSPECTION_SAFE: "Safety tips",
//         // 教程管理                                                              Tutorial management",
//         COURSE_MAN: "Tutorial management",
//         COURSE_LIST: "Tutorial list",
//         COURSE_TITLE: "Tutorial title",
//         COURSE_ADD: "Add tutorial",
//         COURSE_EDIT: "Edit tutorial",
//         COURSE_DETAIL: "Tutorial details",
//         COURSE_STATE: "Tutorial status",
//         COURSE_FY: "Tutorial cover page",
//         COURSE_FY_TIP: "Only one image can be uploaded, and the image size is greater than or equal to 80*80 px square image",
//         COURSE_DESC: "Introduction to the tutorial",
//         COURSE_SP: "Video cover image",
//         COURSE_SP_TIP: "Only one image can be uploaded, and the image size is limited to 350*240px",
//         COURSE_VIDEO: "Tutorial video",
//         COURSE_VIDEO_DETAIL: "Tutorial details",
//         //通用                                                                 General",
//         INPUT_RULES1: "Please enter information",
//         INPUT_RULES2: "Do not enter spaces",
//         INPUT_RULES3: "Please enter a positive integer",
//         INPUT_RULES4: "Please enter the correct number (the decimal place does not exceed 2 digits)",
//         INPUT_RULES5: "Please enter the correct phone number",
//         INPUT_RULES6: "Please enter a combination of numbers and letters",
//         INPUT_RULES7: "Maximum length is",
//         INPUT_RULES8: "Minimum length is",
//         INPUT_RULES9: "Minimum length is",
//         INPUT_RULES10: "Minimum length is",
//         PIC_TIP1: "Image not uploaded",
//         PIC_TIP2: "The picture is being uploaded",
//         PIC_TIP3: "Please upload the suggested size",
//         PIC_TIP4: "Image upload was successful",
//         PIC_TIP5: "Please upload the correct image format",
//         PIC_TIP6: "The picture is being uploaded, please wait later",
//         PIC_TIP7: "Please size within 10MB of the image size",
//         PIC_TIP8: "Please upload the correct image format",
//         PIC_TIP9: "Video not uploaded",
//         PIC_TIP10: "Video is uploading",
//         PIC_TIP11: "Video upload is successful",
//         PIC_TIP12: "Video is uploading, please wait",
//         OTA_TIP1: "The firmware package must not be larger than 50M",
//         OTA_TIP2: "Selected file",
//         OTA_TIP3: "Unselected files",
//         REPORT_TIP_DL1: "Motor controller power tube failure",
//         REPORT_TIP_DL2: "Motor controller drive power failure",
//         REPORT_TIP_DL3: "Motor controller overcurrent protection",
//         REPORT_TIP_DL4: "Motor controller overvoltage protection",
//         REPORT_TIP_DL5: "Motor controller undervoltage protection",
//         REPORT_TIP_DL6: "Motor controller over temperature protection",
//         REPORT_TIP_DL7: "Motor controller system failure",
//         REPORT_TIP_DL8: "Motor blocking protection",
//         REPORT_TIP_DL9: "Motor phase line fault",
//         REPORT_TIP_DL10: "Motor Hall Fault",
//         REPORT_TIP_DL11: "Motor over temperature protection",
//         REPORT_TIP_DL12: "Motor power reduction protection",
//         REPORT_TIP_DL13: "Brake failure",
//         REPORT_TIP_DL14: "Turnover fault (beyond the valid value of the handle)",
//         REPORT_TIP_DL15: "Turnover fault (power-on switch is not reset)",
//         REPORT_TIP_EL1: "Battery charging temperature is too high protection",
//         REPORT_TIP_EL2: "Battery charging temperature is too low protection",
//         REPORT_TIP_EL3: "Battery discharge temperature is too high protection",
//         REPORT_TIP_EL4: "Battery discharge temperature is too low protection",
//         REPORT_TIP_EL5: "Battery drop protection",
//         REPORT_TIP_EL6: "Battery high voltage protection",
//         REPORT_TIP_EL7: "Battery MOSFET temperature is too high",
//         REPORT_TIP_EL8: "Battery cell overvoltage protection",
//         REPORT_TIP_EL9: "Battery cell low voltage protection",
//         REPORT_TIP_EL10: "Battery pack low voltage protection",
//         REPORT_TIP_EL11: "Battery charging overcurrent protection",
//         REPORT_TIP_EL12: "Battery discharge overcurrent protection",
//         REPORT_TIP_EL13: "Battery charging port short circuit protection",
//         REPORT_TIP_EL14: "Battery discharge port short circuit protection",
//         REPORT_TIP_EL15: "Battery battery short circuit protection",
//         REPORT_TIP_EL16: "Charger temperature is too high protection",
//         REPORT_TIP_EL17: "The charger MOSFET temperature is too high",
//         REPORT_TIP_EL18: "Charger output short circuit protection",
//         REPORT_TIP_EL19: "The charger input voltage is too low",
//         REPORT_TIP_EL20: "The charger input voltage is too high",
//         REPORT_TIP_EL21: "The charger input voltage is unstable",
//         REPORT_TIP_EL22: "12V power failure",
//         REPORT_TIP_AF1: "Faucet lock failure",
//         REPORT_TIP_AF2: "Medium lock failure",
//         REPORT_TIP_AF3: "Barrel lock failure",
//         REPORT_TIP_AF4: "Tailbox lock failure",
//         REPORT_TIP_AF5: "Brake lock failure",
//         REPORT_TIP_AF6: "Theft is malfunctioning",
//         REPORT_TIP_TX1: "VCU (Central Control) and controller communication failure",
//         REPORT_TIP_TX2: "VCU (Central Control) and instrument communication failure",
//         REPORT_TIP_TX3: "VCU (Central Control) communication failure with the lamp driver",
//         REPORT_TIP_TX4: "VCU (Central Control) and BMS communication failure",
//         REPORT_TIP_TX5: "VCU (Central Control) and charger communication failure",
//         REPORT_TIP_TX6: "VCU (Central Control) and the anti-theft device communication failure",
//         REPORT_TIP_TX7: "VCU (Central Control) communication failure",
//         REPORT_TIP_TX8: "Gyro failure",
//         REPORT_TIP_ZM1: "Left turn signal failure",
//         REPORT_TIP_ZM2: "Right turn signal failure",
//         REPORT_TIP_ZM3: "Large turn signal failure",
//         REPORT_TIP_ZM4: "Fog light failure",
//         REPORT_TIP_ZM5: "Brake light failure",
//         REPORT_TIP_ZM6: "Aura (light) malfunction"
//     },
//     "zh-CN": {
//         ACCOUNT: "账号",
//         PASSWORD: "密码",
//         LOG_In: "登录",
//         LOG_OUT: "退出登录",
//         ChANG_PASSWORD: "修改密码",
//         CurrentPassword: "当前密码",
//         NEWPassword: "新密码",
//         AGAIN_NEWPassword: "再次输入新密码",
//         SUBMIT: "提交",
//         SURE: "确认",
//         CANCEL: "取消",
//         CLOSE: "关闭",
//         ADMIN_MANAGEMENT: "后台管理",
//         // 数据概览
//         DATA_BOARD: "数据概览",
//         VEHICLE: "车辆",
//         USER: "用户",
//         VEHICLE_ALL_NUM: "车辆总数",
//         VEHICLE_ONLINE: "在线车辆",
//         VEHICLE_OFFLINE: "离线车辆",
//         VEHICLE_NEW: "近30天新绑车辆",
//         DATA_VEHICLE_LOCATION: "当前车辆分布",
//         DATA_VEHICLE_CITY: "车辆所在城市",
//         DATA_VEHICLE_NEW: "新绑定车辆数",
//         DATA_VEHICLE_SALE: "售出车辆总数（绑定APP）",
//         DATA_VEHICLE_SALE_CITY: "车辆售出（绑定APP）城市TOP10",
//         RANK: "排行",
//         CITY: "城市",
//         VEHICLE_NUM: "车辆数",
//         DATE: "日期",
//         USER_ALL_NUM: "用户总数",
//         DATA_USER_NEW: "新注册用户",
//         DATA_USER_LOCATION: "用户所在地区分布",
//         DATA_USER_CITY: "用户所在城市TOP10",
//         USER_NUM: "用户数",
//         // 车辆管理
//         BREADCRUMB_VEHICLE: "车辆管理",
//         VEHICLE_LIST: "车辆列表",
//         VEHICLE_ID_CODE: "车辆识别码",
//         FRAME_ID: "车架号",
//         VCU_ID: "VCU编号",
//         VEHICLE_TYPE: "车型",
//         CONFIGURATION_ID: "配置编号",
//         OWNER_ID: "车主账号",
//         FIRST_BIND_LOCATION: "第一次绑定地区",
//         FIRST_BIND_DATE: "第一次绑定时间",
//         CONNECTION: "是否在线",
//         LAST_ONLINE_TIME: "最后在线时间",
//         OPERATION: "操作",
//         IMPORT_VEHICLES: "导入车辆",
//         DOWNLOAD_VEHICLES: "导出车辆",
//         DETAIL: "详情",
//         DRIVING_RECORD: "行驶记录",
//         REPORT_BOOK: "体检报告",
//         ONLINE: "在线",
//         OFFLINE: "离线",
//         ALL: "全部",
//         TOTAL: "共",
//         // 车辆详情
//         VEHICLE_DETAIL: "车辆详情",
//         VEHICLE_DETAIL_INFO: "车辆基础信息",
//         VEHICLE_DETAIL_PARTS: "车辆配件信息",
//         VEHICLE_DETAIL_USE: "车辆使用情况",
//         VEHICLE_DETAIL_SERVICE: "当前智能服务",
//         VEHICLE_DETAIL_OWNER: "车主信息",
//         VEHICLE_COLOR: "颜色",
//         VEHICLE_UPDATE: "更新",
//         VEHICLE_CONFIG: "车型配置",
//         VIEW_MORE: "查看更多",
//         VEHICLE_CLOSE: "收起",
//         VEHICLE_LOCKING: "远程锁车",
//         VEHICLE_LOCKING_TIP: "是否确定锁车？",
//         VEHICLE_DJ: "电机号",
//         VEHICLE_KZQ: "电机控制器编号",
//         VEHICLE_YB: "仪表编号",
//         VEHICLE_BMS: "BMS编号",
//         VEHICLE_CDQ: "充电器编号",
//         VEHICLE_BJQ: "报警器编号",
//         VEHICLE_DGKZ: "灯光控制器编号",
//         VEHICLE_USE_DATE: "使用时间（天）",
//         VEHICLE_TRIP: "累计行程（km）",
//         VEHICLE_TRIP_TIME: "累计行驶时间",
//         VEHICLE_NOW_lOC: "车辆当前位置",
//         VEHICLE_SPEED: "平均速度",
//         VEHICLE_SPEED_MUST: "最高速度",
//         HOUR: "小时",
//         MINUTE: "分钟",
//         SECOND: "秒",
//         VIEW: "查看",
//         VEHICLE_NOW_lOC_DETAIL: "查看车辆当前位置",
//         GPS: "GPS坐标",
//         ADDRESS: "地址",
//         UPDATE_TIME: "更新时间",
//         DRIVING_RECORD_DETAIL: "查看行驶记录",
//         PACKAGE_TYPE: "套餐类型",
//         MATURITY_TIME: "到期时间",
//         MAIN_ACCOUNT: "主账户",
//         SUB_ACCOUNT: "从账户",
//         BINDING_TIME: "绑定时间",
//         UNBINDING_TIME: "解绑时间",
//         HISTORIC_OWNERS: "历史车主",
//         HISTORIC_OWNERS_DETAIL: "查看历史车主信息",
//         UNBOUND_VEHICLES: "解绑车辆",
//         UNBOUND_VEHICLES_TIP: "是否确定解绑车辆？",
//         MODIFY: "修改",
//         SAVE: "保存",
//         // 车辆行驶历史
//         DRIVING_RECORD_HIS: "车辆行驶历史",
//         DRIVING_RECORD_LJXS: "累计行驶",
//         DRIVING_TIME_START: "骑行时间（始）",
//         DRIVING_TIME_END: "骑行时间（终）",
//         START_LOC: "起点",
//         END_LOC: "终点",
//         DRIVING_KM: "行驶里程(km)",
//         DRIVING_TIME: "行驶时间",
//         TRAJECTORY: "轨迹",
//         TRAJECTORY_VIEW: "查看轨迹",
//         TRAJECTORY_DETAIL: "车辆行驶轨迹",
//         // 车辆体检报告
//         VEHICLES_REPORT_BOOK: "体检报告",
//         REPORT_RESULT: "体检结果",
//         REPORT_NUM: "体检次数",
//         REPORT_DL: "动力系统异常次数",
//         REPORT_DY: "电源系统异常次数",
//         REPORT_AF: "安防系统异常次数",
//         REPORT_TX: "通信系统异常次数",
//         REPORT_ZM: "照明系统异常次数",
//         REPORT_TIME: "体检时间",
//         REPORT_XT_DL: "动力系统",
//         REPORT_XT_DY: "电源系统",
//         REPORT_XT_AF: "安防系统",
//         REPORT_XT_TX: "通信系统",
//         REPORT_XT_ZM: "照明系统",
//         NORMAL: "正常",
//         ABNORMAL: "异常",
//         HAVE_ABNORMAL: "有异常",
//         REPORT_AB_DL: "动力系统异常",
//         REPORT_AB_DY: "电源系统异常",
//         REPORT_AB_AF: "安防系统异常",
//         REPORT_AB_TX: "通信系统异常",
//         REPORT_AB_ZM: "照明系统异常",
//         REPORT_DETAIL: "体检报告详情",
//         // 车型管理
//         VEHICLE_TYPE_MAN: "车型管理",
//         PICTURE: "图片",
//         IS_PICTURE: "有无图片",
//         IS_PICTURE_YES: "有",
//         IS_PICTURE_NO: "无",
//         VEHICLE_TYPE_IMPORT: "导入车型",
//         VEHICLE_TYPE_ADD: "添加车型",
//         EDIT: "编辑",
//         DELETE: "删除",
//         VEHICLE_TYPE_INFO: "车型信息",
//         VEHICLE_TYPE_INFO_TIP1: "(已与车辆关联的车型、配置编号、颜色不可编辑)",
//         VEHICLE_TYPE_INFO_TIP2: "1.安全范围470PX x 470PX （车辆尺寸范围）",
//         VEHICLE_TYPE_INFO_TIP3: "2.文件尺寸为500PX x 512PX",
//         VEHICLE_TYPE_INFO_TIP4: "3.产品用尽量用实物图，背景色建议透明最优，或者背景色为#F9F9F9",
//         DELETE_TIP: "是否确定删除？",
//         // 用户管理
//         USER_MAN: "用户管理",
//         USER_LIST: "用户列表",
//         USER_ID: "用户账号",
//         REAL_NAME: "真实姓名",
//         GENDER: "性别",
//         USER_AREA: "所在区域",
//         REGISTRATION_TIME: "注册时间",
//         STATUS: "状态",
//         USER_EXPORT: "导出用户",
//         DISABLE: "禁用",
//         ABLE: "启用",
//         DISABLE_TIP: "是否确定禁用？",
//         ABLE_TIP: "是否确定启用？",
//         USER_CARD_ID: "身份证号",
//         BIRTH: "生日",
//         IDENTITY: "身份",
//         HISTORICAL_VEHICLES: "历史车辆",
//         // 消息管理
//         MSG_MAN: "消息管理",
//         MSG_LIST: "消息管理列表",
//         MSG_TITLE: "消息主题",
//         MSG_TYPE: "消息类型",
//         MSG_TIME: "推送时间",
//         MSG_ADD: "添加消息",
//         MSG_EDIT: "编辑消息",
//         MSG_TYPE_TZ: "通知",
//         MSG_TYPE_HD: "活动",
//         MSG_TYPE_QT: "其他",
//         MSG_DISC: "消息描述",
//         MSG_DETAIL: "消息内容",
//         MSG_TIME_INTERVAL: "定时发布",
//         MSG_AREA: "发布区域",
//         MSG_SELECT_AREA: "选择区域",
//         MSG_URL: "添加外部链接",
//         MSG_IMAGE: "主题图片",
//         MSG_IMAGE_TIP: "(图片尺寸690*284px。)",
//         MSG_SELECT_AREA_TIP: "请选择区域",
//         //反馈管理
//         FEEDBACK_MAN: "反馈管理",
//         FEEDBACK_LIST: "反馈列表",
//         FEEDBACK_TYPE: "反馈类型",
//         FEEDBACK_DETAIL: "反馈内容",
//         FEEDBACK_TIME: "反馈时间",
//         EXPORT: "导出列表",
//         FEEDBACK_DETAIL_VIEW: "反馈信息",
//         FEEDBACK_DETAIL_TIP: "点击查看图片详情",
//         //员工管理
//         STAFF_MAN: "员工管理",
//         ROLE_LIST: "角色列表",
//         ROLE_NAME: "角色名称",
//         ROLE_ID: "角色编号",
//         ROLE_ADD: "添加角色",
//         ROLE_EDIT: "编辑角色",
//         REMARK: "备注",
//         ROLE_DISTRIBUTION: "分配角色",
//         //员工账号管理
//         STAFF_LIST: "员工账号列表",
//         STAFF_USER_NAME: "用户名",
//         STAFF_NAME: "姓名",
//         ROLE: "角色",
//         TELEPHONE: "手机",
//         CREATED_TIME: "创建时间",
//         STAFF_LAST_LOGIN: "最后登录时间",
//         STAFF_LAST_IP: "最后登录IP",
//         STAFF_INFO: "员工账号信息",
//         // 操作日志
//         LOG_LIST: "操作日志",
//         TIME: "时间",
//         // 固件升级管理
//         Firmware_MAN: "固件升级管理",
//         Firmware_UPDATE: "固件升级",
//         Firmware_ID: "部件产品编号",
//         Firmware_OLD_Version: "原固件版本",
//         Firmware_NEW_Version: "升级后固件版本",
//         Firmware_Version_Description: "固件版本说明",
//         Firmware_UPDATE_ADD: "升级固件",
//         Firmware_OLD_Version_NO: "原固件版本号",
//         Firmware_NEW_Version_NP: "新固件版本号",
//         Firmware_UPDATE_TYPE: "升级类型",
//         Firmware_Version_Description_NEW: "新固件版本说明",
//         Firmware_FORCE: "强制",
//         Firmware_USER_SELECTION: "用户自选",
//         Firmware_UPDATE_Version: "升级后固件版本号",
//         Firmware_UPDATE_Version_DOWOND: "升级后固件下载",
//         Firmware_UPDATE_Version_Description: "升级后固件版本说明",
//         Firmware_TIP1: "个部件升级中.",
//         Firmware_TIP2: "个部件等待升级中.",
//         Firmware_TIP3: "个部件升级成功.",
//         Firmware_TIP4: "台车辆掉线.",
//         Firmware_TIP5: "台设备 VCU下载失败.",
//         Firmware_TIP6: "台设备  485传输失败.",
//         Firmware_TIP7: "台设备  固件升级失败.",
//         Firmware_TIP8: "台设备  485传输失败.",
//         SEND_AGAIN: "再次发送",
//         RE_DOWNLOAD: "重新下载",
//         // OTA 固件包
//         OTA_LIST: "OTA 固件包",
//         Firmware_Version: "固件版本",
//         OTA_Version_Description: "版本描述",
//         ADD_TIME: "添加时间",
//         OTA_ADD: "添加固件",
//         Version_ID: "版本号",
//         OTA_BAG: "固件包",
//         OTA_Description: "描述",
//         // 广告管理
//         ADVERTISING_MAN: "广告管理",
//         ADVERTISING_EDIT: "更换广告",
//         ADVERTISING_EDIT_TIP: "(图片尺寸750*1334 px，建议图片主体不超过710*1334px。)",
//         ADVERTISING_RELEASE: "发布",
//         //    APP管理
//         APP_MAN: "APP管理",
//         APP_NAME: "版本名称",
//         APP_TYPE: "APP类型",
//         APP_SYS: "操作系统类型",
//         APP_TIME: "版本时间",
//         APP_ADD: "添加APP版本",
//         APP_UPLOAD: "上传",
//         APP_LOG: "版本更新日志",
//         // 新闻管理
//         NEWS_MAN: "新闻管理",
//         NEWS_LIST: "新闻列表",
//         NEWS_TITLE: "新闻标题",
//         NEWS_TOP: "是否置顶",
//         NEWS_TIME: "发布时间",
//         NEWS_ADD: "添加新闻",
//         NEWS_EDIT: "编辑新闻",
//         NEWS_NOW_PUSH: "立即发布",
//         NEWS_FY: "封页图片",
//         NEWS_FY_TIP: "(只允许上传一张图片，图片尺寸大于或等于80*80 px的方形图片)",
//         NEWS_DISC: "新闻简介",
//         NEWS_DETAIL: "新闻详情",
//         // 自检手册管理
//         INSPECTION_MAN: "自检手册管理",
//         INSPECTION_CLASSIFICATION: "自检手册分类",
//         INSPECTION_TYPE: "自检类型",
//         INSPECTION_RANK: "排序",
//         INSPECTION_SON: "子集",
//         INSPECTION_SON_AREA: "子集区域",
//         INSPECTION_CLASSIFICATION_EDIT: "编辑自检分类",
//         // 自检内容管理
//         INSPECTION_CONTENT: "自检内容管理",
//         INSPECTION_TITLE: "自检标题",
//         INSPECTION_ASSOCIATION_TYPE: "关联类型",
//         INSPECTION_CODE: "关联故障码",
//         INSPECTION_ADD: "添加自检内容",
//         INSPECTION_EDIT: "编辑自检内容",
//         INSPECTION_DETAIL: "自检内容详情",
//         INSPECTION_DESC: "问题症状",
//         INSPECTION_PROBLEM_DETAIL: "问题详情",
//         INSPECTION_SOLVE: "解决方案",
//         INSPECTION_SAFE: "安全提示",
//         // 教程管理
//         COURSE_MAN: "教程管理",
//         COURSE_LIST: "教程列表",
//         COURSE_TITLE: "教程标题",
//         COURSE_ADD: "添加教程",
//         COURSE_EDIT: "编辑教程",
//         COURSE_DETAIL: "教程详情",
//         COURSE_STATE: "教程状态",
//         COURSE_FY: "教程封页",
//         COURSE_FY_TIP: "只允许上传一张图片，图片尺寸大于或等于80*80 px的方形图片",
//         COURSE_DESC: "教程简介",
//         COURSE_SP: "视频封面图片",
//         COURSE_SP_TIP: "只允许上传一张图片，图片尺寸限制为350*240px的图片",
//         COURSE_VIDEO: "教程视频",
//         COURSE_VIDEO_DETAIL: "教程详情",
//         //通用
//         INPUT_RULES1: "请输入信息",
//         INPUT_RULES2: "请勿输入空格",
//         INPUT_RULES3: "请输入正整数",
//         INPUT_RULES4: "请输入正确数字（小数位不超过2位）",
//         INPUT_RULES5: "请输入正确的电话",
//         INPUT_RULES6: "请输入数字和字母组合",
//         INPUT_RULES7: "最大长度为",
//         INPUT_RULES8: "最小长度为",
//         INPUT_RULES9: "最小长度为",
//         INPUT_RULES10: "最小长度为",
//         PIC_TIP1: "图片未上传",
//         PIC_TIP2: "图片正在上传",
//         PIC_TIP3: "请上传建议的尺寸",
//         PIC_TIP4: "图片上传成功",
//         PIC_TIP5: "请上传正确的图片格式",
//         PIC_TIP6: "图片正在上传，请稍后",
//         PIC_TIP7: "图片大小请在10MB以内",
//         PIC_TIP8: "请上传正确的图片格式",
//         PIC_TIP9: "视频未上传",
//         PIC_TIP10: "视频正在上传",
//         PIC_TIP11: "视频上传成功",
//         PIC_TIP12: "视频正在上传，请稍后",
//         OTA_TIP1: "固件包不得大于50M",
//         OTA_TIP2: "选定文件",
//         OTA_TIP3: "未选定文件",
//         REPORT_TIP_DL1: "电机控制器功率管故障",
//         REPORT_TIP_DL2: "电机控制器驱动电源故障",
//         REPORT_TIP_DL3: "电机控制器过流保护",
//         REPORT_TIP_DL4: "电机控制器过压保护",
//         REPORT_TIP_DL5: "电机控制器欠压保护",
//         REPORT_TIP_DL6: "电机控制器过温保护",
//         REPORT_TIP_DL7: "电机控制器系统故障",
//         REPORT_TIP_DL8: "电机堵转保护",
//         REPORT_TIP_DL9: "电机相线故障",
//         REPORT_TIP_DL10: "电机霍尔故障",
//         REPORT_TIP_DL11: "电机过温保护",
//         REPORT_TIP_DL12: "电机降功率保护",
//         REPORT_TIP_DL13: "刹车故障",
//         REPORT_TIP_DL14: "转把故障（超出转把有效值）",
//         REPORT_TIP_DL15: "转把故障（上电转把未复位）",
//         REPORT_TIP_EL1: "电池充电温度过高保护",
//         REPORT_TIP_EL2: "电池充电温度过低保护",
//         REPORT_TIP_EL3: "电池放电温度过高保护",
//         REPORT_TIP_EL4: "电池放电温度过低保护",
//         REPORT_TIP_EL5: "电池掉线保护",
//         REPORT_TIP_EL6: "电池高压保护",
//         REPORT_TIP_EL7: "电池MOSFET温度过高",
//         REPORT_TIP_EL8: "电池电芯过压保护",
//         REPORT_TIP_EL9: "电池电芯低压保护",
//         REPORT_TIP_EL10: "电池组低压保护",
//         REPORT_TIP_EL11: "电池充电过流保护",
//         REPORT_TIP_EL12: "电池放电过流保护",
//         REPORT_TIP_EL13: "电池充电口短路保护",
//         REPORT_TIP_EL14: "电池放电口短路保护",
//         REPORT_TIP_EL15: "电池电芯短路保护",
//         REPORT_TIP_EL16: "充电器温度过高保护",
//         REPORT_TIP_EL17: "充电器MOSFET温度过高",
//         REPORT_TIP_EL18: "充电器输出口短路保护",
//         REPORT_TIP_EL19: "充电器输入电压过低",
//         REPORT_TIP_EL20: "充电器输入电压过高",
//         REPORT_TIP_EL21: "充电器输入电压不稳",
//         REPORT_TIP_EL22: "12V电源故障",
//         REPORT_TIP_AF1: "龙头锁故障",
//         REPORT_TIP_AF2: "中撑锁故障",
//         REPORT_TIP_AF3: "座桶锁故障",
//         REPORT_TIP_AF4: "尾箱锁故障",
//         REPORT_TIP_AF5: "刹车锁故障",
//         REPORT_TIP_AF6: "防盗器故障",
//         REPORT_TIP_TX1: "VCU（中控）与控制器通信故障",
//         REPORT_TIP_TX2: "VCU（中控）与仪表通信故障",
//         REPORT_TIP_TX3: "VCU（中控）与灯具驱动器通信故障",
//         REPORT_TIP_TX4: "VCU（中控）与BMS通信故障",
//         REPORT_TIP_TX5: "VCU（中控）与充电器通信故障",
//         REPORT_TIP_TX6: "VCU（中控）与防盗器通信故障",
//         REPORT_TIP_TX7: "VCU（中控）通信故障",
//         REPORT_TIP_TX8: "陀螺仪故障",
//         REPORT_TIP_ZM1: "左转向灯故障",
//         REPORT_TIP_ZM2: "右转向灯故障",
//         REPORT_TIP_ZM3: "大转向灯故障",
//         REPORT_TIP_ZM4: "雾灯故障",
//         REPORT_TIP_ZM5: "刹车灯故障",
//         REPORT_TIP_ZM6: "氛围灯（行车灯）故障",
//     }
// };
// let status = store.getState();
// export const LanguageConfig = languageList[status.language];