""
        ACCOUNT:"Account",
        PASSWORD:"Password",
        LOG_In:"Login",
        LOG_OUT:"Logout",
        ChANG_PASSWORD:"Change password",
        CurrentPassword:"Current password",
        NEWPassword:"New password",
        AGAIN_NEWPassword:"Enter new password again",
        SUBMIT:"Submit",
        SURE:"Confirm",
        CANCEL:"Cancel",
        CLOSE:"Close",
        ADMIN_MANAGEMENT:"Background management",
        // 数据概览                                                              Data overview",
        DATA_BOARD:"Data overview",
        VEHICLE:"Vehicle",
        USER:"User",
        VEHICLE_ALL_NUM:"Total number of vehicles",
        VEHICLE_ONLINE:"Online vehicles",
        VEHICLE_OFFLINE:"Offline vehicle",
        VEHICLE_NEW:"Newly tied vehicles in the last 30 days",
        DATA_VEHICLE_LOCATION:"Current vehicle distribution",
        DATA_VEHICLE_CITY:"The city where the vehicle is located",
        DATA_VEHICLE_NEW:"Number of newly bound vehicles",
        DATA_VEHICLE_SALE:"Total number of vehicles sold (bind APP)",
        DATA_VEHICLE_SALE_CITY:"Vehicle sold (bind APP) city TOP10",
        RANK:"Ration",
        CITY:"City",
        VEHICLE_NUM:"Number of vehicles",
        DATE:"Date",
        USER_ALL_NUM:"Total number of users",
        DATA_USER_NEW:"New registered user",
        DATA_USER_LOCATION:"The distribution of the user's location",
        DATA_USER_CITY:"User's city TOP10",
        USER_NUM:"Number of users",
        // 车辆管理                                                              Vehicle management",
        BREADCRUMB_VEHICLE:"Vehicle management",
        VEHICLE_LIST:"Vehicle list",
        VEHICLE_ID_CODE:"Vehicle identification number",
        FRAME_ID:"frame number",
        VCU_ID:"VCU number",
        VEHICLE_TYPE:"Model",
        CONFIGURATION_ID:"Configuration number",
        OWNER_ID:"Car owner account",
        FIRST_BIND_LOCATION:"First binding area",
        FIRST_BIND_DATE:"First bind time",
        CONNECTION:"Is it online",
        LAST_ONLINE_TIME:"Last online time",
        OPERATION:"Operation",
        IMPORT_VEHICLES:"Import vehicle",
        DOWNLOAD_VEHICLES:"Export vehicle",
        DETAIL:"Details",
        DRIVING_RECORD:"Travel record",
        REPORT_BOOK:"Physical examination report",
        ONLINE:"Online",
        OFFLINE:"Offline",
        ALL:"All",
        TOTAL:"Total",
        // 车辆详情                                                              Vehicle details",
        VEHICLE_DETAIL:"Vehicle details",
        VEHICLE_DETAIL_INFO:"Vehicle basic information",
        VEHICLE_DETAIL_PARTS:"Vehicle accessories information",
        VEHICLE_DETAIL_USE:"Vehicle usage",
        VEHICLE_DETAIL_SERVICE:"Current smart service",
        VEHICLE_DETAIL_OWNER:"Car owner information",
        VEHICLE_COLOR:"Color",
        VEHICLE_UPDATE:"Update",
        VEHICLE_CONFIG:"Model configuration",
        VIEW_MORE:"View more",
        VEHICLE_CLOSE:"Put away",
        VEHICLE_LOCKING:"Remote lock car",
        VEHICLE_LOCKING_TIP:"Are you sure to lock the car",
        VEHICLE_DJ:"Motor no",
        VEHICLE_KZQ:"Motor controller number",
        VEHICLE_YB:"Meter number",
        VEHICLE_BMS:"BMS number",
        VEHICLE_CDQ:"Charger number",
        VEHICLE_BJQ:"Alarm number",
        VEHICLE_DGKZ:"Lighting controller number",
        VEHICLE_USE_DATE:"Usage time (days)",
        VEHICLE_TRIP:"Accumulated trip (km)",
        VEHICLE_TRIP_TIME:"Accumulated driving time",
        VEHICLE_NOW_lOC:"The current location of the vehicle",
        VEHICLE_SPEED:"Average speed",
        VEHICLE_SPEED_MUST:"Maximum speed",
        HOUR:"Hours",
        MINUTE:"Minutes",
        SECOND:"Second",
        VIEW:"View",
        VEHICLE_NOW_lOC_DETAIL:"View the current location of the vehicle",
        GPS:"GPS coordinates",
        ADDRESS:"Address",
        UPDATE_TIME:"Update time",
        DRIVING_RECORD_DETAIL:"View driving history",
        PACKAGE_TYPE:"Package type",
        MATURITY_TIME:"Expiration time",
        MAIN_ACCOUNT:"Primary account",
        SUB_ACCOUNT:"From account",
        BINDING_TIME:"Binding time",
        UNBINDING_TIME:"Untie time",
        HISTORIC_OWNERS:"History owner",
        HISTORIC_OWNERS_DETAIL:"View historical owner information",
        UNBOUND_VEHICLES:"Untie the vehicle",
        UNBOUND_VEHICLES_TIP:"Are you sure to untie the vehicle?",
        MODIFY:"Modify",
        SAVE:"Save",
        // 车辆行驶历史                                                            Vehicle history",
        DRIVING_RECORD_HIS:"Vehicle driving history",
        DRIVING_RECORD_LJXS:"Accumulated driving",
        DRIVING_TIME_START:"Riding time (starting)",
        DRIVING_TIME_END:"ride time (final)",
        START_LOC:"Starting point",
        END_LOC:"End point",
        DRIVING_KM:"Traveling miles (km)",
        DRIVING_TIME:"Travel time",
        TRAJECTORY:"Track",
        TRAJECTORY_VIEW:"View tracks",
        TRAJECTORY_DETAIL:"Vehicle trajectory",
        // 车辆体检报告                                                            Vehicle medical report",
        VEHICLES_REPORT_BOOK:"Physical examination report",
        REPORT_RESULT:"Physical examination result",
        REPORT_NUM:"Number of physical exams",
        REPORT_DL:"Power system abnormal number",
        REPORT_DY:"Power system abnormal number",
        REPORT_AF:"Security aystem abnormal number of times",
        REPORT_TX:"Number of communication system anomalies",
        REPORT_ZM:"Number of illumination system anomalies",
        REPORT_TIME:"Physical examination time",
        REPORT_XT_DL:"Power aystem",
        REPORT_XT_DY:"Power aystem",
        REPORT_XT_AF:"Security System",
        REPORT_XT_TX:"Communication system",
        REPORT_XT_ZM:"Lighting system",
        NORMAL:"Normal",
        ABNORMAL:"Exception",
        HAVE_ABNORMAL:"There is an exception",
        REPORT_AB_DL:"Power system abnormal",
        REPORT_AB_DY:"Power system is abnormal",
        REPORT_AB_AF:"Security system abnormal",
        REPORT_AB_TX:"Communication system exception",
        REPORT_AB_ZM:"The lighting system is abnormal",
        REPORT_DETAIL:"Details of the medical report",
        // 车型管理                                                              Model management",
        VEHICLE_TYPE_MAN:"Model management",
        PICTURE:"Picture",
        IS_PICTURE:"Have a picture？",
        IS_PICTURE_YES:"Yes",
        IS_PICTURE_NO:"None",
        VEHICLE_TYPE_IMPORT:"Imported models",
        VEHICLE_TYPE_ADD:"Add a model",
        EDIT:"Edit",
        DELETE:"Delete",
        VEHICLE_TYPE_INFO:"Model information",
        VEHICLE_TYPE_INFO_TIP1:"The model, configuration number, and color that are associated with the vehicle are not editable",
        VEHICLE_TYPE_INFO_TIP2:"1. Safe Range 470PX x 470PX (Vehicle Size Range)",
        VEHICLE_TYPE_INFO_TIP3:"2. The file size is 500PX x 512PX",
        VEHICLE_TYPE_INFO_TIP4:"3. Try to use the physical map as much as possible, the background color is recommended to be transparent, or the background color is #F9F9F9",
        DELETE_TIP:"Are you sure to delete?",
        // 用户管理                                                              User management",
        USER_MAN:"User management",
        USER_LIST:"User list",
        USER_ID:"User account",
        REAL_NAME:"Real name",
        GENDER:"Gender",
        USER_AREA:"Zone in the area",
        REGISTRATION_TIME:"Registration time",
        STATUS:"Status",
        USER_EXPORT:"Export user",
        DISABLE:"Disabled",
        ABLE:"Enable",
        DISABLE_TIP:"Are you sure to disable?",
        ABLE_TIP:"Are you sure to enable?",
        USER_CARD_ID:"ID number",
        BIRTH:"Birthday",
        IDENTITY:"Identity",
        HISTORICAL_VEHICLES:"Historical vehicles",
        // 消息管理                                                              message management",
        MSG_MAN:"Message management",
        MSG_LIST:"Message management list",
        MSG_TITLE:"message topic",
        MSG_TYPE:"message type",
        MSG_TIME:"Push time",
        MSG_ADD:"Add message",
        MSG_EDIT:"Edit message",
        MSG_TYPE_TZ:"Notification",
        MSG_TYPE_HD:"Activity",
        MSG_TYPE_QT:"Other",
        MSG_DISC:"Message description",
        MSG_DETAIL:"Message content",
        MSG_TIME_INTERVAL:"Timed release",
        MSG_AREA:"Publishing area",
        MSG_SELECT_AREA:"Select region",
        MSG_URL:"Add external link",
        MSG_IMAGE:"Theme Picture",
        MSG_IMAGE_TIP:"(image size 690*284px.)",
        MSG_SELECT_AREA_TIP:"Please select a region",
        //反馈管理                                                               Feedback management",
        FEEDBACK_MAN:"Feedback management",
        FEEDBACK_LIST:"Feedback list",
        FEEDBACK_TYPE:"Feedback type",
        FEEDBACK_DETAIL:"Feedback content",
        FEEDBACK_TIME:"Feedback time",
        EXPORT:"Export list",
        FEEDBACK_DETAIL_VIEW:"Feedback information",
        FEEDBACK_DETAIL_TIP:"Click to view image details",
        //员工管理                                                               Employee management",
        STAFF_MAN:"Employee management",
        ROLE_LIST:"role list",
        ROLE_NAME:"role name",
        ROLE_ID:"role number",
        ROLE_ADD:"Add a role",
        ROLE_EDIT:"Edit role",
        REMARK:"Remarks",
        ROLE_DISTRIBUTION:"Assign a role",
        //员工账号管理                                                             Staff account management",
        STAFF_LIST:"Employee account list",
        STAFF_USER_NAME:"Username",
        STAFF_NAME:"Name",
        ROLE:"Role",
        TELEPHONE:"Mobile phone",
        CREATED_TIME:"Create time",
        STAFF_LAST_LOGIN:"Last login time",
        STAFF_LAST_IP:"Last login iP",
        STAFF_INFO:"Employee account information",
        // 操作日志                                                              Operation log",
        LOG_LIST:"Operation log",
        TIME:"Time",
        // 固件升级管理                                                            Firmware upgrade management",
        Firmware_MAN:"Firmware upgrade management",
        Firmware_UPDATE:"Firmware upgrade",
        Firmware_ID:"Part product number",
        Firmware_OLD_Version:"Original firmware version",
        Firmware_NEW_Version:"Upgrade firmware version",
        Firmware_Version_Description:"Firmware version description",
        Firmware_UPDATE_ADD:"Upgrade firmware",
        Firmware_OLD_Version_NO:"Original firmware version number",
        Firmware_NEW_Version_NP:"New firmware version number",
        Firmware_UPDATE_TYPE:"Upgrade type",
        Firmware_Version_Description_NEW:"New firmware release Notes",
        Firmware_FORCE:"Forced",
        Firmware_USER_SELECTION:"User-selected",
        Firmware_UPDATE_Version:"Upgrade firmware version number",
        Firmware_UPDATE_Version_DOWOND:"Upgrade firmware download",
        Firmware_UPDATE_Version_Description:"Upgrade firmware version description",
        Firmware_TIP1:"Parts are being upgraded",
        Firmware_TIP2:"The components are waiting for the upgrade",
        Firmware_TIP3:"The components have been upgraded successfully",
        Firmware_TIP4:"The vehicle is dropped",
        Firmware_TIP5:"The device vCU download failed",
        Firmware_TIP6:"Taiwan device 485 transmission failed",
        Firmware_TIP7:"The device firmware failed to upgrade",
        Firmware_TIP8:"The device 485 transmission failed.",
        SEND_AGAIN:"Send again",
        RE_DOWNLOAD:"Re-download",
        // OTA 固件包                                                           OTA firmware package",
        OTA_LIST:"OTA firmware package",
        Firmware_Version:"Firmware version",
        OTA_Version_Description:"Version description",
        ADD_TIME:"Add time",
        OTA_ADD:"Add firmware",
        Version_ID:"Version number",
        OTA_BAG:"Firmware pack",
        OTA_Description:"Description",
        // 广告管理                                                              Advertising management",
        ADVERTISING_MAN:"Advertising management",
        ADVERTISING_EDIT:"Replace ads",
        ADVERTISING_EDIT_TIP:"Image size 750*1334 px, it is recommended that the image body does not exceed 710*1334px.",
        ADVERTISING_RELEASE:"Publish",
    //    APP管理                                                              APP management",
        APP_MAN:"APP management",
        APP_NAME:"Version name",
        APP_TYPE:"APP type",
        APP_SYS:"Operating system type",
        APP_TIME:"Version time",
        APP_ADD:"Add aPP version",
        APP_UPLOAD:"Upload",
        APP_LOG:"Version update log",
        // 新闻管理                                                              News management",
        NEWS_MAN:"News management",
        NEWS_LIST:"News list",
        NEWS_TITLE:"News headline",
        NEWS_TOP:"Is it topped",
        NEWS_TIME:"Publish time",
        NEWS_ADD:"Add news",
        NEWS_EDIT:"Editing news",
        NEWS_NOW_PUSH:"Immediately released",
        NEWS_FY:"Cover image",
        NEWS_FY_TIP:"Only one image can be uploaded, the image size is greater than or equal to 80*80 px square image",
        NEWS_DISC:"News introduction",
        NEWS_DETAIL:"News details",
        // 自检手册管理                                                            Self-test manual management",
        INSPECTION_MAN:"Self-test manual management",
        INSPECTION_CLASSIFICATION:"Self-test manual classification",
        INSPECTION_TYPE:"Self-test type",
        INSPECTION_RANK:"Sort",
        INSPECTION_SON:"Subset",
        INSPECTION_SON_AREA:"Subset area",
        INSPECTION_CLASSIFICATION_EDIT:"Edit self-test classification",
        // 自检内容管理                                                            Self-test content management",
        INSPECTION_CONTENT:"Self-test content management",
        INSPECTION_TITLE:"Self-test title",
        INSPECTION_ASSOCIATION_TYPE:"association type",
        INSPECTION_CODE:"Associated fault code",
        INSPECTION_ADD:"Add self-test content",
        INSPECTION_EDIT:"Edit self-test content",
        INSPECTION_DETAIL:"Self-test content details",
        INSPECTION_DESC:"problem symptom",
        INSPECTION_PROBLEM_DETAIL:"Uestion details",
        INSPECTION_SOLVE:"Solution",
        INSPECTION_SAFE:"Safety tips",
        // 教程管理                                                              Tutorial management",
        COURSE_MAN:"Tutorial management",
        COURSE_LIST:"Tutorial list",
        COURSE_TITLE:"Tutorial title",
        COURSE_ADD:"Add tutorial",
        COURSE_EDIT:"Edit tutorial",
        COURSE_DETAIL:"Tutorial details",
        COURSE_STATE:"Tutorial status",
        COURSE_FY:"Tutorial cover page",
        COURSE_FY_TIP:"Only one image can be uploaded, and the image size is greater than or equal to 80*80 px square image",
        COURSE_DESC:"Introduction to the tutorial",
        COURSE_SP:"Video cover image",
        COURSE_SP_TIP:"Only one image can be uploaded, and the image size is limited to 350*240px",
        COURSE_VIDEO:"Tutorial video",
        COURSE_VIDEO_DETAIL:"Tutorial details",
        //通用                                                                 General",
        INPUT_RULES1:"Please enter information",
        INPUT_RULES2:"Do not enter spaces",
        INPUT_RULES3:"Please enter a positive integer",
        INPUT_RULES4:"Please enter the correct number (the decimal place does not exceed 2 digits)",
        INPUT_RULES5:"Please enter the correct phone number",
        INPUT_RULES6:"Please enter a combination of numbers and letters",
        INPUT_RULES7:"Maximum length is",
        INPUT_RULES8:"Minimum length is",
        INPUT_RULES9:"Minimum length is",
        INPUT_RULES10:"Minimum length is",
        PIC_TIP1:"Image not uploaded",
        PIC_TIP2:"The picture is being uploaded",
        PIC_TIP3:"Please upload the suggested size",
        PIC_TIP4:"Image upload was successful",
        PIC_TIP5:"Please upload the correct image format",
        PIC_TIP6:"The picture is being uploaded, please wait later",
        PIC_TIP7:"Please size within 10MB of the image size",
        PIC_TIP8:"Please upload the correct image format",
        PIC_TIP9:"Video not uploaded",
        PIC_TIP10:"Video is uploading",
        PIC_TIP11:"Video upload is successful",
        PIC_TIP12:"Video is uploading, please wait",
        OTA_TIP1:"The firmware package must not be larger than 50M",
        OTA_TIP2:"Selected file",
        OTA_TIP3:"Unselected files",
        REPORT_TIP_DL1:"Motor controller power tube failure",
        REPORT_TIP_DL2:"Motor controller drive power failure",
        REPORT_TIP_DL3:"Motor controller overcurrent protection",
        REPORT_TIP_DL4:"Motor controller overvoltage protection",
        REPORT_TIP_DL5:"Motor controller undervoltage protection",
        REPORT_TIP_DL6:"Motor controller over temperature protection",
        REPORT_TIP_DL7:"Motor controller system failure",
        REPORT_TIP_DL8:"Motor blocking protection",
        REPORT_TIP_DL9:"Motor phase line fault",
        REPORT_TIP_DL10:"Motor Hall Fault",
        REPORT_TIP_DL11:"Motor over temperature protection",
        REPORT_TIP_DL12:"Motor power reduction protection",
        REPORT_TIP_DL13:"Brake failure",
        REPORT_TIP_DL14:"Turnover fault (beyond the valid value of the handle)",
        REPORT_TIP_DL15:"Turnover fault (power-on switch is not reset)",
        REPORT_TIP_EL1:"Battery charging temperature is too high protection",
        REPORT_TIP_EL2:"Battery charging temperature is too low protection",
        REPORT_TIP_EL3:"Battery discharge temperature is too high protection",
        REPORT_TIP_EL4:"Battery discharge temperature is too low protection",
        REPORT_TIP_EL5:"Battery drop protection",
        REPORT_TIP_EL6:"Battery high voltage protection",
        REPORT_TIP_EL7:"Battery MOSFET temperature is too high",
        REPORT_TIP_EL8:"Battery cell overvoltage protection",
        REPORT_TIP_EL9:"Battery cell low voltage protection",
        REPORT_TIP_EL10:"Battery pack low voltage protection",
        REPORT_TIP_EL11:"Battery charging overcurrent protection",
        REPORT_TIP_EL12:"Battery discharge overcurrent protection",
        REPORT_TIP_EL13:"Battery charging port short circuit protection",
        REPORT_TIP_EL14:"Battery discharge port short circuit protection",
        REPORT_TIP_EL15:"Battery battery short circuit protection",
        REPORT_TIP_EL16:"Charger temperature is too high protection",
        REPORT_TIP_EL17:"The charger MOSFET temperature is too high",
        REPORT_TIP_EL18:"Charger output short circuit protection",
        REPORT_TIP_EL19:"The charger input voltage is too low",
        REPORT_TIP_EL20:"The charger input voltage is too high",
        REPORT_TIP_EL21:"The charger input voltage is unstable",
        REPORT_TIP_EL22:"12V power failure",
        REPORT_TIP_AF1:"Faucet lock failure",
        REPORT_TIP_AF2:"Medium lock failure",
        REPORT_TIP_AF3:"Barrel lock failure",
        REPORT_TIP_AF4:"Tailbox lock failure",
        REPORT_TIP_AF5:"Brake lock failure",
        REPORT_TIP_AF6:"Theft is malfunctioning",
        REPORT_TIP_TX1:"VCU (Central Control) and controller communication failure",
        REPORT_TIP_TX2:"VCU (Central Control) and instrument communication failure",
        REPORT_TIP_TX3:"VCU (Central Control) communication failure with the lamp driver",
        REPORT_TIP_TX4:"VCU (Central Control) and BMS communication failure",
        REPORT_TIP_TX5:"VCU (Central Control) and charger communication failure""",
        REPORT_TIP_TX6:"VCU (Central Control) and the anti-theft device communication failure",
        REPORT_TIP_TX7:"VCU (Central Control) communication failure",
        REPORT_TIP_TX8:"Gyro failure",
        REPORT_TIP_ZM1:"Left turn signal failure",
        REPORT_TIP_ZM2:"Right turn signal failure",
        REPORT_TIP_ZM3:"Large turn signal failure",
        REPORT_TIP_ZM4:"Fog light failure",
        REPORT_TIP_ZM5:"Brake light failure",
        REPORT_TIP_ZM6:"Aura (light) malfunction",