
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quartz?useUnicode=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: larschengScheduler1
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 5000
            useProperties: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
#          dataSource:
#            default:
#              URL: jdbc:mysql://localhost:3306/quartz?characterEncoding=utf-8
#              user: root
#              password: 123456
#              driver: com.mysql.jdbc.Driver
    job-store-type: jdbc

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.lars.www.entity
server:
  port: 8999


